name: nuberu
description: Dart ORM
version: 0.0.1
#homepage: https://www.example.com
#author: aitor <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  meta: ^1.1.2
  inflection: ^0.4.1
  logging: ^0.11.3
  sqljocky5: ^1.0.0

dev_dependencies:
  test: ^0.12.0
